var x = 5;
var y = 10;
var z = "10";
var isMorning = true;
var isAfternoon = false;
console.log("Is x < y? I predict true.");
console.log(x < y);
console.log("Is isMorning true? I predict true.");
console.log(isMorning);
console.log("Is x > y? I predict false.");
console.log(x > y);
